### ISSUE TITLE
Can I use this ORM with Cake 2.x?

### ISSUE THREAD

**Issue by backstageel** [cakephp/orm#2]
I have a huge Cakephp project with almost 200 tables using cake 2.x. I want to do gradual upgrade to cake 3.x, so i want that some models use cake 3 ORM while others still use cake2.x models.

Is it possible to work like this? if so, is there any tutorial on how to do this?

Thanks in advance

**Comment by josegonzalez** [comment]
@lorenzo @jippi

**Comment by markstory** [comment]
Yes it is theoretically possible. Is there a tutorial - No.

**Comment by andre-pdassis** [comment]
I would recommend you to take a look at CakePHP Cookbook section [Upgrade Tool](http://book.cakephp.org/3.0/en/upgrade-tool.html) and @markstory post [Upgrading to CakePHP 3.0](http://mark-story.com/posts/view/upgrading-to-cakephp-3-0).

**Comment by sulian** [comment]
A tutorial is a good idea ; I have also a big application  (5 sub modules, almost 100 tables) and I don't know where to start in order to migrate it...

@andtxr , I have read the upgrade guide but it is obscur for me and somes commands won't work even with the last version (move to new folder structure for example).

Anyway thanks to all the team for the job, I use cakephp since 2 years and I don't regret that.

**Comment by ramiroaraujo** [comment]
I'm currently using Cake  3 ORM with a cake2 app. It wasn't that straight forward, but not that hard after all. What I couldn't try yet, and I assume wont be easy/possible, is to integrate the cake2 FormHelper with the Table class.

The basic integration process is:
1. have the cake2 app working with composer, at the very least have the composer autoloader initialized correctly, and have the autoload section properly defined in you composer.json. In my case I have the app folder with cake, and app/src with my project files, and the autload section looks like this: `
   "autoload": {
   "psr-4": {
     "App\\": "src"
   }
   },`
2. require the ORM, probably cake 3 cache, maybe the log
3. define the CONFIG const, required by the cake 3 Configure class: `if (!defined('CONFIG')) define('CONFIG', APP . 'Config' . DS);`
4. load the cake 3 Configure class with at least the App.namespace key, being the same as the specified one in composer.json, in my case: `'App.namespace' => 'App'`
5. manually configure cake 3 ConnectionManager with the proper ddbb config/credentials.
6. configure cake 3 Cache and Log if required

After this steps, calling `TableRegistry::get('SomeModel')` will work as expected, given you have the Table and Entity classes in Model/Table and Model/Entity.

Finally, for this project I setup a companion cake 3 app to bake all the entities and table classes, since it's quite helpful. 

As you see, quite the workout just for having the ORM working. It's probably worth it if you need it for services or anything not view + form related. If I cannot find a way to somehow partially integrate it with the FormHelper I'll have to duplicate validation and maybe some other business logic in the cake2 models and that wont be that neat.

**Comment by GRufusC** [comment]
https://qiita.com/kunit/items/f00d232baead413ba223#comments This site has a more detailed example of a cakephp2 app using the cake3 ORM.
